### ISSUE TITLE
Blocked on: Alpine.js tools loading

### ISSUE THREAD

**Issue by bdbais** [alpine-collective/alpinejs-devtools#135] opened 2020-12-20 14:18 UTC
I'm stuck, never worked.
Is it possible to know what is doing in this state?

Alpine.js tools loading

**Comment by HugoDF** [comment] 2020-12-20 20:55
@bdbais do you have a link to the app where this is happening? Anything in the logs?

**Comment by ChrisKniight** [comment] 2020-12-31 12:43
I'm encountering the same issue on a local project.

Chrome 87.0.4280.88
"Allow access to file URL" granted

**Comment by HugoDF** [comment] 2020-12-31 16:42
@ChrisKniight any way you can share the app causing issues?

**Comment by HugoDF** [comment] 2021-01-05 18:54
Closing this since no reproduction steps/failing app have been shared.

Feel free to re-open with a link to a page or a code repository with which this issue occurs.

**Closed by HugoDF** 2021-01-05 18:54 UTC
Labels: bug
